// <auto-generated />
using System;
using FoodDelivery.DAL.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodDelivery.Migrations
{
    [DbContext(typeof(FoodDeliveryContext))]
    [Migration("20190322002643_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodDelivery.DAL.Models.Basket", b =>
                {
                    b.Property<int>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BasketId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("FoodDelivery.DAL.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new { Id = 1, CategoryName = "Category1", Description = "Description1" },
                        new { Id = 2, CategoryName = "Category2", Description = "Description2" }
                    );
                });

            modelBuilder.Entity("FoodDelivery.DAL.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double>("Percentage");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new { Id = 1, Description = "Description1", Percentage = 0.05 },
                        new { Id = 2, Description = "Descripiton2", Percentage = 0.1 }
                    );
                });

            modelBuilder.Entity("FoodDelivery.DAL.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasketId");

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<int?>("DiscountId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, Description = "Description1", Name = "Item1" },
                        new { Id = 2, CategoryId = 1, Description = "Description2", Name = "Item2" },
                        new { Id = 3, CategoryId = 1, Description = "Description3", DiscountId = 2, Name = "Item3" },
                        new { Id = 4, CategoryId = 1, Description = "Description4", DiscountId = 1, Name = "Item4" },
                        new { Id = 5, CategoryId = 1, Description = "Description5", Name = "Item5" }
                    );
                });

            modelBuilder.Entity("FoodDelivery.DAL.Models.MenuItem", b =>
                {
                    b.HasOne("FoodDelivery.DAL.Models.Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
