using System.ComponentModel; 

namespace FoodDelivery.DAL.Models.Enums
{
    public enum Region
    {
        [Description("AutonomousRepublicofCrimea")]
        AutonomousRepublicOfCrimea,
        [Description("CherkasyRegion")]
        CherkasyRegion,
        [Description("ChernihivRegion")]
        ChernihivRegion,
        [Description("ChernivtsiRegion")]
        ChernivtsiRegion,
        [Description("DnipropetrovskRegion")]
        DnipropetrovskRegion,
        [Description("DonetskRegion")]
        DonetskRegion,
        [Description("IvanoFrankivskRegion")]
        IvanoFrankivskRegion,
        [Description("KharkivRegion")]
        KharkivRegion,
        [Description("KhersonRegion")]
        KhersonRegion,
        [Description("KhmelnytskyRegion")]
        KhmelnytskyRegion,
        [Description("KirovogradRegion")]
        KirovogradRegion,
        [Description("KyivRegion")]
        KyivRegion,
        [Description("LuhanskRegion")]
        LuhanskRegion,
        [Description("LvivRegion")]
        LvivRegion,
        [Description("MykolayivRegion")]
        MykolayivRegion,
        [Description("OdesaRegion")]
        OdesaRegion,
        [Description("PoltavaRegion")]
        PoltavaRegion,
        [Description("RivneRegion")]
        RivneRegion,
        [Description("SumyRegion")]
        SumyRegion,
        [Description("TernopilRegion")]
        TernopilRegion,
        [Description("TheCityoOfKyiv")]
        TheCityOfKyiv,
        [Description("VinnytsyaRegion")]
        VinnytsyaRegion,
        [Description("VolynRegion")]
        VolynRegion,
        [Description("ZakarpattyaRegion")]
        ZakarpattyaRegion,
        [Description("ZaporizhzhyaRegion")]
        ZaporizhzhyaRegion,
        [Description("ZhytomyrRegion")]
        ZhytomyrRegion,
        [Description("TheCityOfSevastopol")]
        TheCityOfSevastopol
    }
}